export const skills: string[] = [
  "Overall",
	"Attack",
	"Defence",
	"Strength",
	"Hitpoints",
	"Ranged",
	"Prayer",
	"Magic",
	"Cooking",
	"Woodcutting",
	"Fletching",
	"Fishing",
	"Firemaking",
	"Crafting",
	"Smithing",
	"Mining",
	"Herblore",
	"Agility",
	"Thieving",
	"Slayer",
	"Farming",
	"Runecrafting",
	"Hunter",
	"Construction",
];

export const activities: string[] = [
  "Bounty Hunter - Hunter",
	"Bounty Hunter - Rogues",
	"Clue Scrolls All",
	"Clue Scrolls Easy",
	"Clue Scrolls Medium",
	"Clue Scrolls Hard",
	"Clue Scrolls Elite",
	"Clue Scrolls Master",
	"LMS Rank",
]